export default [
    { label: 'Angular', file: 'angular' },
    { label: 'Astro', file: 'astro' },
    { label: 'Bootstrap', file: 'bootstrap' },
    { label: 'CSS', file: 'css' },
    { label: 'Firebase', file: 'firebase' },
    { label: 'Gatsby', file: 'gatsby' },
    { label: 'Git', file: 'git' },
    { label: 'GraphQL', file: 'graphql' },
    { label: 'HTML', file: 'html' },
    { label: 'Javascript', file: 'javascript' },
    { label: 'Laravel', file: 'laravel' },
    { label: 'Material UI', file: 'mui' },
    { label: 'PHP', file: 'php' },
    { label: 'Postgres', file: 'postgres' },
    { label: 'Python', file: 'python' },
    { label: 'React', file: 'react' },
    { label: 'Redux', file: 'redux' },
    { label: 'Sass', file: 'sass' },
    { label: 'Typescript', file: 'typescript' },
    { label: 'Vue', file: 'vue' },
];
